<a href="https://colab.research.google.com/github/saniya-stud/NumPY/blob/main/pythondemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3],dtype='int32')
print(a)
b=np.array([[3.0,4.0,5.0],[9.0,8.0,1.0]])
print(b)

#getshape
a.ndim
b.ndim
#getshape
a.shape #it says 3
b.shape
#it says 2/3 matrix


#type
a.dtype
b.dtype

#size(no of bits in a data type)
a.itemsize #if int16 itemsize=2,if int32 itemsize=4
b.itemsize
#total size
a.size*a.itemsize
a.nbytes



[1 2 3]
[[3. 4. 5.]
 [9. 8. 1.]]


12