<a href="https://colab.research.google.com/github/saniya-stud/NumPY/blob/main/pythondemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
a=np.array([1,2,3],dtype='int32')
print(a)
b=np.array([[3.0,4.0,5.0],[9.0,8.0,1.0]])
print(b)

#getshape
a.ndim
b.ndim
#getshape
a.shape #it says 3
b.shape
#it says 2/3 matrix


#type
a.dtype
b.dtype

#size(no of bits in a data type)
a.itemsize #if int16 itemsize=2,if int32 itemsize=4
b.itemsize
#total size
a.size*a.itemsize
a.nbytes



[1 2 3]
[[3. 4. 5.]
 [9. 8. 1.]]


12

In [26]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

a[1,2]
a[:,1]#specific column

a[1,:]#specific row

a[0,1:-1:2]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([2, 4])

In [35]:
a[1,2]=20
print(a)

a[:,2]=[1,2]
print(a)


[[ 1  2  3  4  5]
 [ 6  7 20  9 10]]
[[ 1  2  1  4  5]
 [ 6  7  2  9 10]]


In [33]:
a[0,0:5:2]

array([1, 3, 5])

In [43]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,5,6]]])
print(a)
a[1,:,2] #2nd bracket,all rows,2nd column(1.9)
a[0,0,:] #(1,2,3) all in row
a[0,:,0] #all in column (1,4)
a[:,0,1]

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 5 6]]]


array([2, 8])

In [52]:
#initializing types of arrays
np.zeros((2,3))
np.ones((4,1,2),dtype="int32")




array([[[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]]], dtype=int32)

In [54]:
np.full((3,2),99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [55]:

np.full_like(a,3) #||np,full(a.shape,3)
#created 3/3 because a is also 3/3 before

array([[[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]]])

In [56]:
np.random.rand(1,2)

array([[0.97721396, 0.61759024]])

In [62]:
#repeats an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))

z[1,1]=9
print(z)

output[1:-1,1:-1]=z #copying z into op
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
#copying
a=([1,2,3])
#b=a
b=a.copy()
b[1]=300
print(b)

[1, 300, 3]


In [75]:
np.random.rand(2,3)

array([[0.5769029 , 0.70188972, 0.60419843],
       [0.66465205, 0.96717237, 0.76160465]])

In [79]:
np.random.randint(3,size=(3,3))

array([[0, 2, 0],
       [0, 2, 0],
       [0, 2, 2]])

In [84]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [80]:
arr=np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
#maths
a=np.array([1,2,3,4])
a
a+2
a-3
a/2
a%2
b=np.array([5,6,7,8])
b+a
b**3
np.sin(a)
np.cos(b)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [106]:
#linear algebra
a=np.ones((2,3))
print(a)
b=np.full((3,4),2)
print(b)
c=np.matmul(a,b)
print(c)



[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [109]:
#determinant
b=np.identity(3)
np.linalg.det(b)

np.float64(1.0)

In [115]:
#statistics
stats=np.array([[1,2,3,4],[5,6,7,8]])
print(stats)
np.min(stats)
np.max(stats)
np.sum(stats)

[[1 2 3 4]
 [5 6 7 8]]


np.int64(36)

In [118]:
#reorganizing arrays
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((2,2,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
#vertical stacking
v1=np.array([1,2,3])
v2=np.array([6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3],
       [6, 7, 8],
       [1, 2, 3],
       [6, 7, 8]])

In [122]:
#h stacking
h1=np.array([1,2,3])
h2=np.array([6,7,8])
np.hstack([h1,h2])


array([1, 2, 3, 6, 7, 8])